version: '2'
services:
  one-ws24:
    build: '.'
    volumes:
      - ./descriptors:/descriptors
  lb:
    image: dockercloud/haproxy
    links:
      - one-ws24
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 80:80
